import type {
  Categoria,
  Institucion,
  Licitacion,
  PerfilCapacidad,
} from "./types";

/**
 * Reference data for the LicitaRD platform.
 *
 * The tenders below are realistic, representative samples of Dominican public
 * procurement (institutions, procedure types, DOP values, schedules) used to
 * demonstrate the search / organize / track experience. They are illustrative
 * and not pulled from any live feed — the data layer is shaped so a real
 * DGCP / OCDS feed can be dropped in behind the same types.
 */

export const PLATFORM = {
  name: "LicitaRD",
  tagline: "Inteligencia de licitaciones públicas",
  descripcion:
    "Busca, organiza y da seguimiento a todas las licitaciones del Estado dominicano desde un solo lugar, con alertas, puntuación de afinidad y analítica de adjudicaciones.",
  pais: "República Dominicana",
  fuente: "Portal Transaccional · DGCP",
} as const;

export const INSTITUCIONES: Institucion[] = [
  { id: "msp", nombre: "Ministerio de Salud Pública", sigla: "MSP", tipo: "Ministerio" },
  { id: "minerd", nombre: "Ministerio de Educación", sigla: "MINERD", tipo: "Ministerio" },
  { id: "mopc", nombre: "Ministerio de Obras Públicas y Comunicaciones", sigla: "MOPC", tipo: "Ministerio" },
  { id: "mived", nombre: "Ministerio de la Vivienda y Edificaciones", sigla: "MIVED", tipo: "Ministerio" },
  { id: "inabie", nombre: "Instituto Nacional de Bienestar Estudiantil", sigla: "INABIE", tipo: "Institución Autónoma" },
  { id: "inapa", nombre: "Instituto Nacional de Aguas Potables y Alcantarillados", sigla: "INAPA", tipo: "Institución Autónoma" },
  { id: "caasd", nombre: "Corporación del Acueducto y Alcantarillado de Santo Domingo", sigla: "CAASD", tipo: "Empresa Pública" },
  { id: "edesur", nombre: "Empresa Distribuidora de Electricidad del Sur", sigla: "EDESUR", tipo: "Empresa Pública" },
  { id: "adn", nombre: "Ayuntamiento del Distrito Nacional", sigla: "ADN", tipo: "Ayuntamiento" },
  { id: "senasa", nombre: "Seguro Nacional de Salud", sigla: "SENASA", tipo: "Institución Autónoma" },
  { id: "intrant", nombre: "Instituto Nacional de Tránsito y Transporte Terrestre", sigla: "INTRANT", tipo: "Institución Autónoma" },
  { id: "mide", nombre: "Ministerio de Defensa", sigla: "MIDE", tipo: "Ministerio" },
  { id: "banreservas", nombre: "Banco de Reservas de la República Dominicana", sigla: "Banreservas", tipo: "Empresa Pública" },
  { id: "ogtic", nombre: "Oficina Gubernamental de Tecnologías de la Información", sigla: "OGTIC", tipo: "Dirección General" },
];

export const CATEGORIAS: Categoria[] = [
  { id: "construccion", nombre: "Construcción y obras", unspsc: "72", icon: "HardHat" },
  { id: "limpieza", nombre: "Limpieza y mantenimiento", unspsc: "76", icon: "Sparkles" },
  { id: "tecnologia", nombre: "Tecnología y software", unspsc: "43", icon: "Cpu" },
  { id: "salud", nombre: "Equipos médicos y farmacia", unspsc: "42", icon: "HeartPulse" },
  { id: "mobiliario", nombre: "Mobiliario y enseres", unspsc: "56", icon: "Armchair" },
  { id: "alimentos", nombre: "Alimentos y bebidas", unspsc: "50", icon: "UtensilsCrossed" },
  { id: "transporte", nombre: "Vehículos y transporte", unspsc: "25", icon: "Truck" },
  { id: "consultoria", nombre: "Servicios profesionales", unspsc: "80", icon: "Briefcase" },
  { id: "energia", nombre: "Energía y electricidad", unspsc: "26", icon: "Zap" },
  { id: "oficina", nombre: "Material de oficina", unspsc: "44", icon: "Paperclip" },
  { id: "textiles", nombre: "Uniformes y textiles", unspsc: "53", icon: "Shirt" },
  { id: "seguridad", nombre: "Seguridad y vigilancia", unspsc: "92", icon: "ShieldCheck" },
];

export const PROVINCIAS = [
  "Nacional (todo el país)",
  "Distrito Nacional",
  "Santo Domingo",
  "Santiago",
  "La Vega",
  "San Cristóbal",
  "Puerto Plata",
  "La Altagracia",
  "San Pedro de Macorís",
  "Barahona",
  "Duarte",
  "Espaillat",
];

/**
 * Default capability profile. It leans toward cleaning, maintenance, facilities
 * and supplies — the profile a services contractor (like the team behind this
 * deployment) would use to surface its best-fit opportunities first.
 */
export const PERFIL_DEFAULT: PerfilCapacidad = {
  nombre: "Servicios generales y mantenimiento",
  categorias: {
    limpieza: 1,
    mobiliario: 0.8,
    textiles: 0.7,
    seguridad: 0.6,
    oficina: 0.6,
    construccion: 0.5,
    consultoria: 0.4,
    alimentos: 0.4,
    transporte: 0.3,
    energia: 0.3,
    tecnologia: 0.3,
    salud: 0.2,
  },
  provinciasPreferidas: ["Distrito Nacional", "Santo Domingo", "Nacional (todo el país)"],
  montoMin: 200_000,
  montoMax: 60_000_000,
};

const doc = (
  nombre: string,
  tipo: "PDF" | "XLSX" | "DOCX" | "ZIP",
  tamano: string,
) => ({ nombre, tipo, tamano });

export const LICITACIONES: Licitacion[] = [
  {
    id: "MSP-CCC-LPN-2026-0012",
    titulo:
      "Servicio de limpieza profunda y mantenimiento sanitario de hospitales del Gran Santo Domingo",
    descripcion:
      "Contratación de servicios de limpieza profunda, desinfección y mantenimiento sanitario para una red de 14 centros hospitalarios del Servicio Nacional de Salud, incluyendo personal, insumos certificados y supervisión por turnos durante 12 meses.",
    institucionId: "msp",
    categoriaId: "limpieza",
    procedimiento: "Licitación Pública Nacional",
    estado: "abierta",
    provincia: "Santo Domingo",
    montoEstimado: 48_500_000,
    moneda: "DOP",
    publicada: "2026-06-02",
    cierre: "2026-06-29",
    apertura: "2026-06-30",
    garantia: 1,
    documentos: [
      doc("Pliego de condiciones específicas", "PDF", "2.4 MB"),
      doc("Formulario de oferta económica", "XLSX", "180 KB"),
      doc("Especificaciones técnicas", "PDF", "1.1 MB"),
    ],
    cronograma: [
      { etapa: "Publicación del proceso", fecha: "2026-06-02", estado: "completado" },
      { etapa: "Consultas y aclaraciones", fecha: "2026-06-16", estado: "actual" },
      { etapa: "Cierre de recepción de ofertas", fecha: "2026-06-29", estado: "pendiente" },
      { etapa: "Apertura de ofertas", fecha: "2026-06-30", estado: "pendiente" },
      { etapa: "Adjudicación", fecha: "2026-07-14", estado: "pendiente" },
    ],
    contacto: { nombre: "Comité de Compras y Contrataciones", email: "compras@msp.gob.do", telefono: "809-541-3121" },
    oferentes: 7,
    destacada: true,
  },
  {
    id: "INABIE-CCC-LPN-2026-0044",
    titulo: "Suministro de raciones alimenticias para el programa de alimentación escolar",
    descripcion:
      "Adquisición y distribución de raciones alimenticias frías y elaboradas para centros educativos del nivel primario en la región Norte, con trazabilidad e inocuidad bajo norma INDOCAL.",
    institucionId: "inabie",
    categoriaId: "alimentos",
    procedimiento: "Licitación Pública Nacional",
    estado: "abierta",
    provincia: "Santiago",
    montoEstimado: 312_000_000,
    moneda: "DOP",
    publicada: "2026-05-28",
    cierre: "2026-07-03",
    apertura: "2026-07-04",
    garantia: 1,
    documentos: [
      doc("Pliego de condiciones", "PDF", "3.8 MB"),
      doc("Listado de centros y rutas", "XLSX", "420 KB"),
    ],
    cronograma: [
      { etapa: "Publicación del proceso", fecha: "2026-05-28", estado: "completado" },
      { etapa: "Reunión aclaratoria", fecha: "2026-06-12", estado: "completado" },
      { etapa: "Cierre de recepción de ofertas", fecha: "2026-07-03", estado: "pendiente" },
      { etapa: "Apertura de ofertas", fecha: "2026-07-04", estado: "pendiente" },
    ],
    contacto: { nombre: "Dirección de Compras INABIE", email: "licitaciones@inabie.gob.do", telefono: "809-732-1500" },
    oferentes: 19,
    destacada: true,
  },
  {
    id: "MOPC-CCC-SO-2026-0078",
    titulo: "Rehabilitación y asfaltado de la carretera Navarrete – Puerto Plata, tramo II",
    descripcion:
      "Obras de rehabilitación, bacheo profundo, drenaje pluvial y asfaltado de 18.4 km de la carretera Navarrete – Puerto Plata, incluyendo señalización horizontal y vertical.",
    institucionId: "mopc",
    categoriaId: "construccion",
    procedimiento: "Sorteo de Obras",
    estado: "por_cerrar",
    provincia: "Puerto Plata",
    montoEstimado: 186_700_000,
    moneda: "DOP",
    publicada: "2026-05-20",
    cierre: "2026-06-17",
    apertura: "2026-06-18",
    garantia: 1,
    documentos: [
      doc("Términos de referencia", "PDF", "5.2 MB"),
      doc("Planos y estudios", "ZIP", "44 MB"),
      doc("Cómputos métricos", "XLSX", "640 KB"),
    ],
    cronograma: [
      { etapa: "Publicación del proceso", fecha: "2026-05-20", estado: "completado" },
      { etapa: "Visita técnica al sitio", fecha: "2026-06-04", estado: "completado" },
      { etapa: "Cierre de recepción de ofertas", fecha: "2026-06-17", estado: "actual" },
      { etapa: "Apertura de sobres", fecha: "2026-06-18", estado: "pendiente" },
    ],
    contacto: { nombre: "Dirección de Contrataciones MOPC", email: "contrataciones@mopc.gob.do", telefono: "809-565-2811" },
    oferentes: 11,
    destacada: true,
  },
  {
    id: "OGTIC-CCC-LPN-2026-0009",
    titulo: "Adquisición de licencias y plataforma de ciberseguridad para el Estado",
    descripcion:
      "Implementación de una plataforma centralizada de detección y respuesta gestionada (XDR/SOC), licenciamiento por 24 meses y transferencia de conocimiento para las instituciones del Gobierno central.",
    institucionId: "ogtic",
    categoriaId: "tecnologia",
    procedimiento: "Licitación Pública Internacional",
    estado: "abierta",
    provincia: "Distrito Nacional",
    montoEstimado: 2_400_000,
    moneda: "USD",
    publicada: "2026-06-05",
    cierre: "2026-07-20",
    apertura: "2026-07-21",
    garantia: 1,
    documentos: [
      doc("Pliego de condiciones (ES/EN)", "PDF", "4.1 MB"),
      doc("Matriz de requerimientos técnicos", "XLSX", "320 KB"),
    ],
    cronograma: [
      { etapa: "Publicación del proceso", fecha: "2026-06-05", estado: "completado" },
      { etapa: "Consultas técnicas", fecha: "2026-06-25", estado: "actual" },
      { etapa: "Cierre de recepción de ofertas", fecha: "2026-07-20", estado: "pendiente" },
      { etapa: "Apertura de ofertas", fecha: "2026-07-21", estado: "pendiente" },
    ],
    contacto: { nombre: "Unidad de Compras OGTIC", email: "compras@ogtic.gob.do", telefono: "809-286-1009" },
    oferentes: 5,
  },
  {
    id: "MSP-CCC-CP-2026-0031",
    titulo: "Adquisición de equipos médicos para unidades de cuidados intensivos",
    descripcion:
      "Compra de ventiladores mecánicos, monitores multiparámetros y bombas de infusión para fortalecer las unidades de cuidados intensivos de hospitales regionales.",
    institucionId: "msp",
    categoriaId: "salud",
    procedimiento: "Comparación de Precios",
    estado: "abierta",
    provincia: "Nacional (todo el país)",
    montoEstimado: 27_900_000,
    moneda: "DOP",
    publicada: "2026-06-08",
    cierre: "2026-06-26",
    apertura: "2026-06-27",
    garantia: 1,
    documentos: [
      doc("Especificaciones técnicas", "PDF", "1.9 MB"),
      doc("Formulario de oferta", "XLSX", "150 KB"),
    ],
    cronograma: [
      { etapa: "Publicación del proceso", fecha: "2026-06-08", estado: "completado" },
      { etapa: "Cierre de recepción de ofertas", fecha: "2026-06-26", estado: "actual" },
      { etapa: "Apertura de ofertas", fecha: "2026-06-27", estado: "pendiente" },
    ],
    contacto: { nombre: "Comité de Compras y Contrataciones", email: "compras@msp.gob.do", telefono: "809-541-3121" },
    oferentes: 9,
  },
  {
    id: "ADN-CCC-CP-2026-0102",
    titulo: "Servicio de recolección y mantenimiento de áreas verdes del Distrito Nacional",
    descripcion:
      "Mantenimiento integral de parques, isletas y áreas verdes: poda, jardinería, riego, recolección de residuos vegetales y reposición de plantas ornamentales por 12 meses.",
    institucionId: "adn",
    categoriaId: "limpieza",
    procedimiento: "Comparación de Precios",
    estado: "por_cerrar",
    provincia: "Distrito Nacional",
    montoEstimado: 14_200_000,
    moneda: "DOP",
    publicada: "2026-05-26",
    cierre: "2026-06-16",
    apertura: "2026-06-17",
    garantia: 1,
    documentos: [
      doc("Pliego de condiciones", "PDF", "1.4 MB"),
      doc("Mapa de zonas a intervenir", "PDF", "2.2 MB"),
    ],
    cronograma: [
      { etapa: "Publicación del proceso", fecha: "2026-05-26", estado: "completado" },
      { etapa: "Cierre de recepción de ofertas", fecha: "2026-06-16", estado: "actual" },
      { etapa: "Apertura de ofertas", fecha: "2026-06-17", estado: "pendiente" },
    ],
    contacto: { nombre: "Comité de Compras ADN", email: "compras@adn.gob.do", telefono: "809-535-1611" },
    oferentes: 6,
    destacada: true,
  },
  {
    id: "MINERD-CCC-LPN-2026-0067",
    titulo: "Mobiliario escolar para 320 aulas de nueva construcción",
    descripcion:
      "Fabricación, suministro y montaje de butacas, mesas, pizarras y mobiliario de oficina para planteles educativos entregados en la jornada extendida.",
    institucionId: "minerd",
    categoriaId: "mobiliario",
    procedimiento: "Licitación Pública Nacional",
    estado: "abierta",
    provincia: "Nacional (todo el país)",
    montoEstimado: 96_300_000,
    moneda: "DOP",
    publicada: "2026-06-01",
    cierre: "2026-07-08",
    apertura: "2026-07-09",
    garantia: 1,
    documentos: [
      doc("Pliego de condiciones", "PDF", "2.8 MB"),
      doc("Fichas técnicas de mobiliario", "PDF", "3.5 MB"),
      doc("Cronograma de entrega por lote", "XLSX", "210 KB"),
    ],
    cronograma: [
      { etapa: "Publicación del proceso", fecha: "2026-06-01", estado: "completado" },
      { etapa: "Consultas", fecha: "2026-06-18", estado: "actual" },
      { etapa: "Cierre de recepción de ofertas", fecha: "2026-07-08", estado: "pendiente" },
      { etapa: "Apertura de ofertas", fecha: "2026-07-09", estado: "pendiente" },
    ],
    contacto: { nombre: "Dirección de Compras MINERD", email: "comprasycontrataciones@minerd.gob.do", telefono: "809-688-9700" },
    oferentes: 14,
  },
  {
    id: "INAPA-CCC-CP-2026-0050",
    titulo: "Suministro de tuberías y accesorios para acueductos rurales",
    descripcion:
      "Adquisición de tuberías de PVC y PEAD, válvulas y accesorios para la ampliación de redes de acueductos rurales en la región Sur.",
    institucionId: "inapa",
    categoriaId: "construccion",
    procedimiento: "Comparación de Precios",
    estado: "cerrada",
    provincia: "Barahona",
    montoEstimado: 21_600_000,
    moneda: "DOP",
    publicada: "2026-05-04",
    cierre: "2026-05-29",
    apertura: "2026-05-30",
    garantia: 1,
    documentos: [doc("Pliego de condiciones", "PDF", "1.7 MB")],
    cronograma: [
      { etapa: "Publicación del proceso", fecha: "2026-05-04", estado: "completado" },
      { etapa: "Cierre de recepción de ofertas", fecha: "2026-05-29", estado: "completado" },
      { etapa: "Evaluación de ofertas", fecha: "2026-06-10", estado: "actual" },
      { etapa: "Adjudicación", fecha: "2026-06-22", estado: "pendiente" },
    ],
    contacto: { nombre: "Comité de Compras INAPA", email: "compras@inapa.gob.do", telefono: "809-567-1818" },
    oferentes: 8,
  },
  {
    id: "EDESUR-CCC-LPN-2025-0211",
    titulo: "Adquisición de transformadores de distribución y materiales de red",
    descripcion:
      "Compra de transformadores monofásicos y trifásicos, conductores y herrajes para el plan de reducción de pérdidas y mejora de la calidad del servicio.",
    institucionId: "edesur",
    categoriaId: "energia",
    procedimiento: "Licitación Pública Internacional",
    estado: "adjudicada",
    provincia: "San Cristóbal",
    montoEstimado: 5_800_000,
    moneda: "USD",
    publicada: "2025-11-12",
    cierre: "2025-12-18",
    apertura: "2025-12-19",
    garantia: 1,
    documentos: [doc("Pliego de condiciones", "PDF", "3.1 MB")],
    cronograma: [
      { etapa: "Publicación del proceso", fecha: "2025-11-12", estado: "completado" },
      { etapa: "Cierre de recepción de ofertas", fecha: "2025-12-18", estado: "completado" },
      { etapa: "Apertura de ofertas", fecha: "2025-12-19", estado: "completado" },
      { etapa: "Adjudicación", fecha: "2026-01-20", estado: "completado" },
    ],
    contacto: { nombre: "Gerencia de Compras EDESUR", email: "compras@edesur.com.do", telefono: "809-683-9292" },
    oferentes: 6,
    adjudicacion: { proveedor: "Electro Suministros del Caribe, SRL", rnc: "1-30-12345-6", monto: 5_640_000, fecha: "2026-01-20" },
  },
  {
    id: "SENASA-CCC-CM-2026-0140",
    titulo: "Servicio de impresión y certificación de carnets de afiliados",
    descripcion:
      "Impresión segura, personalización y distribución de credenciales de afiliados del régimen subsidiado, con elementos de seguridad y trazabilidad.",
    institucionId: "senasa",
    categoriaId: "oficina",
    procedimiento: "Compra Menor",
    estado: "abierta",
    provincia: "Distrito Nacional",
    montoEstimado: 3_450_000,
    moneda: "DOP",
    publicada: "2026-06-09",
    cierre: "2026-06-23",
    apertura: "2026-06-24",
    garantia: 0,
    documentos: [doc("Especificaciones técnicas", "PDF", "780 KB")],
    cronograma: [
      { etapa: "Publicación del proceso", fecha: "2026-06-09", estado: "completado" },
      { etapa: "Cierre de recepción de ofertas", fecha: "2026-06-23", estado: "actual" },
      { etapa: "Apertura de ofertas", fecha: "2026-06-24", estado: "pendiente" },
    ],
    contacto: { nombre: "Departamento de Compras SENASA", email: "compras@senasa.gob.do", telefono: "809-472-8404" },
    oferentes: 4,
  },
  {
    id: "MIDE-CCC-LPN-2026-0019",
    titulo: "Confección y suministro de uniformes militares y calzado de campaña",
    descripcion:
      "Fabricación de uniformes de faena, gala y calzado táctico para las instituciones del Ministerio de Defensa, conforme a especificaciones técnicas y tallaje.",
    institucionId: "mide",
    categoriaId: "textiles",
    procedimiento: "Licitación Pública Nacional",
    estado: "abierta",
    provincia: "Nacional (todo el país)",
    montoEstimado: 73_200_000,
    moneda: "DOP",
    publicada: "2026-06-03",
    cierre: "2026-07-06",
    apertura: "2026-07-07",
    garantia: 1,
    documentos: [
      doc("Pliego de condiciones", "PDF", "2.6 MB"),
      doc("Tabla de tallaje y muestras", "XLSX", "260 KB"),
    ],
    cronograma: [
      { etapa: "Publicación del proceso", fecha: "2026-06-03", estado: "completado" },
      { etapa: "Entrega de muestras", fecha: "2026-06-20", estado: "actual" },
      { etapa: "Cierre de recepción de ofertas", fecha: "2026-07-06", estado: "pendiente" },
      { etapa: "Apertura de ofertas", fecha: "2026-07-07", estado: "pendiente" },
    ],
    contacto: { nombre: "Dirección de Compras MIDE", email: "contrataciones@mide.gob.do", telefono: "809-530-5149" },
    oferentes: 10,
  },
  {
    id: "INTRANT-CCC-CP-2026-0088",
    titulo: "Servicio de vigilancia y seguridad física para oficinas y estaciones",
    descripcion:
      "Provisión de servicios de vigilancia armada y monitoreo para las sedes administrativas y estaciones de revisión técnica vehicular en el Gran Santo Domingo.",
    institucionId: "intrant",
    categoriaId: "seguridad",
    procedimiento: "Comparación de Precios",
    estado: "abierta",
    provincia: "Santo Domingo",
    montoEstimado: 18_900_000,
    moneda: "DOP",
    publicada: "2026-06-06",
    cierre: "2026-06-30",
    apertura: "2026-07-01",
    garantia: 1,
    documentos: [doc("Pliego de condiciones", "PDF", "1.3 MB")],
    cronograma: [
      { etapa: "Publicación del proceso", fecha: "2026-06-06", estado: "completado" },
      { etapa: "Cierre de recepción de ofertas", fecha: "2026-06-30", estado: "pendiente" },
      { etapa: "Apertura de ofertas", fecha: "2026-07-01", estado: "pendiente" },
    ],
    contacto: { nombre: "Comité de Compras INTRANT", email: "compras@intrant.gob.do", telefono: "809-738-4334" },
    oferentes: 7,
  },
  {
    id: "BR-CCC-LPN-2026-0007",
    titulo: "Modernización de cajeros automáticos y kioscos de autoservicio",
    descripcion:
      "Adquisición, instalación y mantenimiento de equipos de autoservicio (ATM y kioscos) con software de gestión y servicio de soporte por 36 meses.",
    institucionId: "banreservas",
    categoriaId: "tecnologia",
    procedimiento: "Licitación Pública Nacional",
    estado: "por_cerrar",
    provincia: "Nacional (todo el país)",
    montoEstimado: 142_000_000,
    moneda: "DOP",
    publicada: "2026-05-22",
    cierre: "2026-06-18",
    apertura: "2026-06-19",
    garantia: 1,
    documentos: [
      doc("Pliego de condiciones", "PDF", "3.4 MB"),
      doc("Anexo de niveles de servicio", "DOCX", "120 KB"),
    ],
    cronograma: [
      { etapa: "Publicación del proceso", fecha: "2026-05-22", estado: "completado" },
      { etapa: "Consultas", fecha: "2026-06-05", estado: "completado" },
      { etapa: "Cierre de recepción de ofertas", fecha: "2026-06-18", estado: "actual" },
      { etapa: "Apertura de ofertas", fecha: "2026-06-19", estado: "pendiente" },
    ],
    contacto: { nombre: "Gerencia de Compras Banreservas", email: "licitaciones@banreservas.com", telefono: "809-960-2000" },
    oferentes: 5,
  },
  {
    id: "CAASD-CCC-CP-2026-0061",
    titulo: "Alquiler de equipos pesados para limpieza de cañadas y drenajes",
    descripcion:
      "Servicio de alquiler de retroexcavadoras, camiones volteo y equipos de succión para jornadas de limpieza de cañadas, imbornales y colectores pluviales.",
    institucionId: "caasd",
    categoriaId: "limpieza",
    procedimiento: "Comparación de Precios",
    estado: "abierta",
    provincia: "Santo Domingo",
    montoEstimado: 11_750_000,
    moneda: "DOP",
    publicada: "2026-06-10",
    cierre: "2026-06-28",
    apertura: "2026-06-29",
    garantia: 1,
    documentos: [doc("Pliego de condiciones", "PDF", "1.0 MB")],
    cronograma: [
      { etapa: "Publicación del proceso", fecha: "2026-06-10", estado: "completado" },
      { etapa: "Cierre de recepción de ofertas", fecha: "2026-06-28", estado: "pendiente" },
      { etapa: "Apertura de ofertas", fecha: "2026-06-29", estado: "pendiente" },
    ],
    contacto: { nombre: "Comité de Compras CAASD", email: "compras@caasd.gob.do", telefono: "809-562-3500" },
    oferentes: 6,
  },
  {
    id: "MIVED-CCC-SO-2026-0033",
    titulo: "Construcción de 240 viviendas de interés social en La Vega",
    descripcion:
      "Construcción de viviendas unifamiliares de interés social con infraestructura básica, calles, aceras y áreas comunes en el proyecto habitacional de La Vega.",
    institucionId: "mived",
    categoriaId: "construccion",
    procedimiento: "Sorteo de Obras",
    estado: "abierta",
    provincia: "La Vega",
    montoEstimado: 410_000_000,
    moneda: "DOP",
    publicada: "2026-06-04",
    cierre: "2026-07-15",
    apertura: "2026-07-16",
    garantia: 1,
    documentos: [
      doc("Términos de referencia", "PDF", "6.0 MB"),
      doc("Planos arquitectónicos", "ZIP", "58 MB"),
    ],
    cronograma: [
      { etapa: "Publicación del proceso", fecha: "2026-06-04", estado: "completado" },
      { etapa: "Visita al sitio", fecha: "2026-06-19", estado: "actual" },
      { etapa: "Cierre de recepción de ofertas", fecha: "2026-07-15", estado: "pendiente" },
      { etapa: "Apertura de ofertas", fecha: "2026-07-16", estado: "pendiente" },
    ],
    contacto: { nombre: "Dirección de Contrataciones MIVED", email: "contrataciones@mived.gob.do", telefono: "809-732-4151" },
    oferentes: 13,
  },
  {
    id: "MINERD-CCC-CP-2026-0098",
    titulo: "Servicio de fumigación y control de plagas en planteles educativos",
    descripcion:
      "Control integral de plagas, desratización y fumigación preventiva en centros educativos de la regional 10 (Santo Domingo), con productos certificados de bajo impacto.",
    institucionId: "minerd",
    categoriaId: "limpieza",
    procedimiento: "Comparación de Precios",
    estado: "adjudicada",
    provincia: "Santo Domingo",
    montoEstimado: 6_900_000,
    moneda: "DOP",
    publicada: "2026-04-10",
    cierre: "2026-05-02",
    apertura: "2026-05-05",
    garantia: 1,
    documentos: [doc("Pliego de condiciones", "PDF", "900 KB")],
    cronograma: [
      { etapa: "Publicación del proceso", fecha: "2026-04-10", estado: "completado" },
      { etapa: "Cierre de recepción de ofertas", fecha: "2026-05-02", estado: "completado" },
      { etapa: "Apertura de ofertas", fecha: "2026-05-05", estado: "completado" },
      { etapa: "Adjudicación", fecha: "2026-05-19", estado: "completado" },
    ],
    contacto: { nombre: "Dirección de Compras MINERD", email: "comprasycontrataciones@minerd.gob.do", telefono: "809-688-9700" },
    oferentes: 5,
    adjudicacion: { proveedor: "Servicios Ambientales Integrales, SRL", rnc: "1-31-98765-4", monto: 6_540_000, fecha: "2026-05-19" },
  },
  {
    id: "OGTIC-CCC-CM-2026-0177",
    titulo: "Servicio de mantenimiento preventivo de centros de datos gubernamentales",
    descripcion:
      "Mantenimiento preventivo y correctivo de UPS, aires de precisión y sistemas de detección de incendios en los centros de datos del Gobierno.",
    institucionId: "ogtic",
    categoriaId: "tecnologia",
    procedimiento: "Compra Menor",
    estado: "abierta",
    provincia: "Distrito Nacional",
    montoEstimado: 4_200_000,
    moneda: "DOP",
    publicada: "2026-06-11",
    cierre: "2026-06-25",
    apertura: "2026-06-26",
    garantia: 0,
    documentos: [doc("Especificaciones técnicas", "PDF", "640 KB")],
    cronograma: [
      { etapa: "Publicación del proceso", fecha: "2026-06-11", estado: "completado" },
      { etapa: "Cierre de recepción de ofertas", fecha: "2026-06-25", estado: "actual" },
      { etapa: "Apertura de ofertas", fecha: "2026-06-26", estado: "pendiente" },
    ],
    contacto: { nombre: "Unidad de Compras OGTIC", email: "compras@ogtic.gob.do", telefono: "809-286-1009" },
    oferentes: 3,
  },
  {
    id: "ADN-CCC-LPN-2026-0120",
    titulo: "Adquisición de camiones compactadores de residuos sólidos",
    descripcion:
      "Compra de camiones compactadores de carga trasera para el fortalecimiento del sistema de recolección de residuos sólidos del Distrito Nacional.",
    institucionId: "adn",
    categoriaId: "transporte",
    procedimiento: "Licitación Pública Nacional",
    estado: "abierta",
    provincia: "Distrito Nacional",
    montoEstimado: 158_000_000,
    moneda: "DOP",
    publicada: "2026-06-07",
    cierre: "2026-07-10",
    apertura: "2026-07-11",
    garantia: 1,
    documentos: [
      doc("Pliego de condiciones", "PDF", "2.1 MB"),
      doc("Especificaciones del chasis", "PDF", "1.4 MB"),
    ],
    cronograma: [
      { etapa: "Publicación del proceso", fecha: "2026-06-07", estado: "completado" },
      { etapa: "Consultas", fecha: "2026-06-22", estado: "actual" },
      { etapa: "Cierre de recepción de ofertas", fecha: "2026-07-10", estado: "pendiente" },
      { etapa: "Apertura de ofertas", fecha: "2026-07-11", estado: "pendiente" },
    ],
    contacto: { nombre: "Comité de Compras ADN", email: "compras@adn.gob.do", telefono: "809-535-1611" },
    oferentes: 8,
  },
  {
    id: "MSP-CCC-CM-2026-0205",
    titulo: "Suministro de insumos de limpieza e higiene para oficinas centrales",
    descripcion:
      "Adquisición de productos de limpieza, desinfectantes, papelería sanitaria y dispensadores para las dependencias administrativas del Ministerio.",
    institucionId: "msp",
    categoriaId: "limpieza",
    procedimiento: "Compra Menor",
    estado: "abierta",
    provincia: "Distrito Nacional",
    montoEstimado: 2_150_000,
    moneda: "DOP",
    publicada: "2026-06-12",
    cierre: "2026-06-24",
    apertura: "2026-06-25",
    garantia: 0,
    documentos: [doc("Lista de insumos requeridos", "XLSX", "90 KB")],
    cronograma: [
      { etapa: "Publicación del proceso", fecha: "2026-06-12", estado: "completado" },
      { etapa: "Cierre de recepción de ofertas", fecha: "2026-06-24", estado: "actual" },
      { etapa: "Apertura de ofertas", fecha: "2026-06-25", estado: "pendiente" },
    ],
    contacto: { nombre: "Comité de Compras y Contrataciones", email: "compras@msp.gob.do", telefono: "809-541-3121" },
    oferentes: 6,
  },
  {
    id: "INAPA-CCC-LPN-2026-0015",
    titulo: "Construcción de planta de tratamiento de aguas residuales en San Pedro",
    descripcion:
      "Diseño y construcción de una planta de tratamiento de aguas residuales con capacidad de 120 l/s, incluyendo obra civil, equipos electromecánicos y puesta en marcha.",
    institucionId: "inapa",
    categoriaId: "construccion",
    procedimiento: "Licitación Pública Internacional",
    estado: "abierta",
    provincia: "San Pedro de Macorís",
    montoEstimado: 8_900_000,
    moneda: "USD",
    publicada: "2026-05-30",
    cierre: "2026-07-22",
    apertura: "2026-07-23",
    garantia: 1,
    documentos: [
      doc("Pliego de condiciones (ES/EN)", "PDF", "7.3 MB"),
      doc("Estudios de ingeniería", "ZIP", "62 MB"),
    ],
    cronograma: [
      { etapa: "Publicación del proceso", fecha: "2026-05-30", estado: "completado" },
      { etapa: "Reunión aclaratoria", fecha: "2026-06-20", estado: "actual" },
      { etapa: "Cierre de recepción de ofertas", fecha: "2026-07-22", estado: "pendiente" },
      { etapa: "Apertura de ofertas", fecha: "2026-07-23", estado: "pendiente" },
    ],
    contacto: { nombre: "Comité de Compras INAPA", email: "compras@inapa.gob.do", telefono: "809-567-1818" },
    oferentes: 9,
  },
  {
    id: "MINERD-CCC-LPN-2026-0150",
    titulo: "Servicio de limpieza y conserjería para centros educativos jornada extendida",
    descripcion:
      "Contratación del servicio de limpieza, conserjería y mantenimiento básico para 96 centros educativos de jornada extendida en la región Este, por 10 meses lectivos.",
    institucionId: "minerd",
    categoriaId: "limpieza",
    procedimiento: "Licitación Pública Nacional",
    estado: "abierta",
    provincia: "La Altagracia",
    montoEstimado: 64_800_000,
    moneda: "DOP",
    publicada: "2026-06-05",
    cierre: "2026-07-02",
    apertura: "2026-07-03",
    garantia: 1,
    documentos: [
      doc("Pliego de condiciones", "PDF", "2.5 MB"),
      doc("Listado de centros", "XLSX", "180 KB"),
    ],
    cronograma: [
      { etapa: "Publicación del proceso", fecha: "2026-06-05", estado: "completado" },
      { etapa: "Consultas", fecha: "2026-06-19", estado: "actual" },
      { etapa: "Cierre de recepción de ofertas", fecha: "2026-07-02", estado: "pendiente" },
      { etapa: "Apertura de ofertas", fecha: "2026-07-03", estado: "pendiente" },
    ],
    contacto: { nombre: "Dirección de Compras MINERD", email: "comprasycontrataciones@minerd.gob.do", telefono: "809-688-9700" },
    oferentes: 12,
    destacada: true,
  },
  {
    id: "EDESUR-CCC-CP-2026-0073",
    titulo: "Servicio de limpieza y mantenimiento de subestaciones eléctricas",
    descripcion:
      "Mantenimiento, desbroce, limpieza técnica y pintura de subestaciones y patios de maniobras de la zona Sur, cumpliendo protocolos de seguridad eléctrica.",
    institucionId: "edesur",
    categoriaId: "limpieza",
    procedimiento: "Comparación de Precios",
    estado: "abierta",
    provincia: "San Cristóbal",
    montoEstimado: 9_300_000,
    moneda: "DOP",
    publicada: "2026-06-09",
    cierre: "2026-06-27",
    apertura: "2026-06-28",
    garantia: 1,
    documentos: [doc("Pliego de condiciones", "PDF", "1.2 MB")],
    cronograma: [
      { etapa: "Publicación del proceso", fecha: "2026-06-09", estado: "completado" },
      { etapa: "Cierre de recepción de ofertas", fecha: "2026-06-27", estado: "actual" },
      { etapa: "Apertura de ofertas", fecha: "2026-06-28", estado: "pendiente" },
    ],
    contacto: { nombre: "Gerencia de Compras EDESUR", email: "compras@edesur.com.do", telefono: "809-683-9292" },
    oferentes: 5,
  },
  {
    id: "BR-CCC-CP-2026-0190",
    titulo: "Servicios de consultoría para transformación digital de procesos internos",
    descripcion:
      "Consultoría especializada para el rediseño y automatización de procesos operativos, gestión del cambio y definición de indicadores de desempeño.",
    institucionId: "banreservas",
    categoriaId: "consultoria",
    procedimiento: "Comparación de Precios",
    estado: "cerrada",
    provincia: "Distrito Nacional",
    montoEstimado: 19_500_000,
    moneda: "DOP",
    publicada: "2026-05-08",
    cierre: "2026-06-02",
    apertura: "2026-06-03",
    garantia: 1,
    documentos: [doc("Términos de referencia", "PDF", "1.6 MB")],
    cronograma: [
      { etapa: "Publicación del proceso", fecha: "2026-05-08", estado: "completado" },
      { etapa: "Cierre de recepción de ofertas", fecha: "2026-06-02", estado: "completado" },
      { etapa: "Evaluación", fecha: "2026-06-13", estado: "actual" },
      { etapa: "Adjudicación", fecha: "2026-06-27", estado: "pendiente" },
    ],
    contacto: { nombre: "Gerencia de Compras Banreservas", email: "licitaciones@banreservas.com", telefono: "809-960-2000" },
    oferentes: 7,
  },
];
